//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace communityassist_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLocation
    {
        public int EventLocationKey { get; set; }
        public string EventLocationName { get; set; }
        public string EventLocationAddress { get; set; }
        public string EventLocationCity { get; set; }
        public string EventLocationState { get; set; }
        public string EventLocationZip { get; set; }
    }
}
